name: Unit Test
on:
    push:
        branches:
            - main

jobs:
    job1:
        name: Tests
        runs-on: ubuntu-latest
        outputs:
            result: ${{ steps.set-result.outputs.result }}
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Python environment configuration
          uses: actions/setup-python@v3
          with:
            python-version: 3.13
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt 
        - name: Run tests
          id: run-tests
          run: python -m unittest -v tests/test_persona.py
        - name: Validate tests with errors
          id: validate-tests-with-errors
          if: ${{ failure() }}
          env:
            ERROR_MESSAGE: "One or more tests failed"
          run: |
            echo "result=${ERROR_MESSAGE}" >> $GITHUB_OUTPUT
        - name: Validate tests without errors
          id: validate-tests-without-errors
          if: ${{ success() }}
          env:
            SUCCESS_MESSAGE: "All tests passed"
          run: |
            echo "result=${SUCCESS_MESSAGE}" >> $GITHUB_OUTPUT
        - name: Set result
          id: set-result
          run: |
            if [ "${{ steps.validate-tests-with-errors.outputs.result }}" ]; then
              echo "result=${{ steps.validate-tests-with-errors.outputs.result }}" >> $GITHUB_OUTPUT
            else
              echo "result=${{ steps.validate-tests-without-errors.outputs.result }}" >> $GITHUB_OUTPUT
            fi
        - name: Coverage report
          id: coverage
          run: |
            coverage run -m unittest tests/test_persona.py
            coverage report -m